name: Bundle Size Analysis

on:
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/bundle-analysis.yml'

jobs:
  analyze_bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: [16.x]

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build:prod

      - name: Run bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: 'build/stats.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
