name: Bundle Size Report with Annotations (CI)

on:
  pull_request:
    branches:
      - master

jobs:
  bundle_size_report:
    name: Bundle Size Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build:prod

      - name: Run bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: 'build/stats.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment bundle size report on PR
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require('fs');

            // Load the bundle size report
            const statsJson = fs.readFileSync('build/stats.json', 'utf8');
            const report = JSON.parse(statsJson);

            // Convert bytes to megabytes
            const bytesToMB = bytes => (bytes / (1024 * 1024)).toFixed(2);

            // Create a formatted list of assets and sizes in MB
            const assetList = report.assets
              .map(asset => `- ${asset.name}: ${bytesToMB(asset.size)} MB`)
              .join('\\n'); // Escape the newline character here

            // Create the comment message
            const comment = "\\nBundle size report:\\n\\n- Total Size: ${bytesToMB(report.totalSize)} MB\\n- Asset Count: ${report.assets.length}\\n\\nAssets:\\n${assetList}";

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
