name: Bundle Size Report with Annotations (CI)
on:
  pull_request:
    branches:
      - master
jobs:
  bundle_size_report:
    name: Bundle Size Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build:prod

      - name: Run bundle-stats
        id: bundle-stats
        uses: vio/bundle-stats-action@v1
        with:
          webpack-stats-path: 'build/stats.json'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR with build statistics
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const stats = require('${{ steps.bundle-stats.outputs.statsPath }}');
            const comment = `Bundle size analysis:\n\n${stats}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
